# Generated by Django 2.2 on 2020-08-22 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_solution', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deliveries',
            new_name='Delivery',
        ),
        migrations.RenameModel(
            old_name='Matches',
            new_name='Match',
        ),
        migrations.RenameModel(
            old_name='Umpires',
            new_name='Umpire',
        ),
    ]
